<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Store</title>
</head>

<body>
    <header>
        <div class="row tm-top-nav tm-b-color-10">
            <div class="col-12">
                <a href="?page=home" class="tm-lnk-0">
                    <p class="tm-color-0 tm-txt-m tm-txt-flt-c">Setup Store</p>
                </a>
            </div>
        </div>
    </header>
    <article>
        <form action="?page=setup_store" method="post">
            <div class="row">
                <div class="col-12">

                </div>
            </div>
            <div class="row">
                <div class="col-12">

                </div>
            </div>
            <br>



            <div class="row">
                <div class="col-12">
                    <p class="tm-txt-s tm-color-13">Store Name</p>
                    <input type="text" name="name" required placeholder="Type here" class="tm-bdr-0 tm-txt-s tm-wd-full tm-outline-0">
                    <hr>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <p class="tm-txt-s tm-color-13">Store Type</p>
                    <input type="text" name="type" required placeholder="Type here" class="tm-bdr-0 tm-txt-s tm-wd-full tm-outline-0">
                    <hr>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <p class="tm-txt-s tm-color-13">Embed Google Map (Enter Source Link)</p>
                    <textarea name="map" required placeholder="Type here" class="tm-bdr-0 tm-txt-s tm-wd-full tm-outline-0" cols="30" rows="10"></textarea>
                    <hr>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <p class="tm-txt-s tm-color-13">Address</p>
                    <input type="text" name="address" required placeholder="Type here" class="tm-bdr-0 tm-txt-s tm-wd-full tm-outline-0">
                    <hr>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <p class="tm-txt-s tm-color-13">Contact</p>
                    <input type="text" name="contact" required placeholder="Type here" class="tm-bdr-0 tm-txt-s tm-wd-full tm-outline-0">
                    <hr>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <p class="tm-txt-s tm-color-13">Description</p>
                    <textarea name="description" required placeholder="Type here" class="tm-bdr-0 tm-txt-s tm-wd-full tm-outline-0" cols="30" rows="10"></textarea>
                    <hr>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <p class="tm-color-13 tm-txt-s"><input type="checkbox" required>Commit </p>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <input type="submit" name="btn_update" value="Update" class="tm-bdr-0 tm-txt-s tm-wd-full tm-outline-0 tm-pd-3 tm-b-color-10 tm-color-0">

                </div>
            </div>
        </form>
    </article>
</body>

</html>