<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Store</title>
</head>

<body class="">
  
    <article>
        <div class="row">
            <div class="col-12">

            </div>
        </div>
        <div class="row">
            <div class="col-12">

            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <center>
                    <img src="<?php echo $config["RES"] . "imgs" . DS . "logo.png"; ?>" class="tm-img-2">
                </center>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <center>
                    <button onclick="location.href='?page=search_store'" class="tm-b-color-10 tm-color-0 tm-txt-s tm-pd-3 tm-txt-flt-c tm-b-color-0 tm-bdr-0 tm-wd-0">
                        Search Store
                    </button>
                </center>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <center>
                    <button onclick="location.href='?page=login'" class="tm-b-color-10 tm-color-0 tm-txt-s tm-pd-3 tm-txt-flt-c tm-b-color-0 tm-bdr-0 tm-wd-0">
                        Log In Store
                    </button>
                </center>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <center>
                    <button  onclick="location.href='?page=register'" class="tm-b-color-10 tm-color-0 tm-txt-s tm-pd-3 tm-txt-flt-c tm-b-color-0 tm-bdr-0 tm-wd-0">
                        Register Store
                    </button>
                </center>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <center>
                    <button onclick="location.href='?page=bookmark'" class="tm-b-color-10 tm-color-0 tm-txt-s tm-pd-3 tm-txt-flt-c tm-b-color-0 tm-bdr-0 tm-wd-0">
                        Bookmark
                    </button>
                </center>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <center>
                    <button onclick="location.href='?page=about'" class="tm-b-color-10 tm-color-0 tm-txt-s tm-pd-3 tm-txt-flt-c tm-b-color-0 tm-bdr-0 tm-wd-0">
                        About
                    </button>
                </center>
            </div>
        </div>
    </article>
    <footer>
        <div class="row">
            <div class="col-12">
                <p class="tm-color-10 tm-txt-s tm-txt-flt-c">Version 1.0.0</p>
            </div>
        </div>
    </footer>
</body>

</html>