<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Store</title>
</head>

<body>
    <header>
        <div class="row tm-top-nav tm-b-color-10">
            <div class="col-12">

                <a href="?page=home" class="tm-lnk-0">
                    <p class="tm-color-0 tm-txt-m tm-txt-flt-c">Store Finder</p>
                </a>

            </div>
        </div>
    </header>
    <article>
        <div class="row">
            <div class="col-12">

            </div>
        </div>
        <div class="row">
            <div class="col-12">

            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <p class="tm-txt-s tm-color-13 tm-txt-flt-c">About</p>

                <p class="tm-txt-s tm-color-13">
                    Customers frequently looked up nearby store locations online. In actuality, this is among the most popular Google searches. Additionally, providing your name, phone number, and location gives your consumers the freedom to interact with your business in whatever way they see fit. Store locators, however, further enhance your content. Possessing vital content is essential for searchability. And more customers equate to more content. A store locator thereby improves the searchability of your company.
                </p>
                <p class="tm-txt-s tm-color-13">
                    Installing store locator software can improve your company's visibility, foster consumer trust and loyalty, enhance website traffic, and help you better understand your customers.
                </p>
                <p class="tm-txt-s tm-color-13">
                    Having a store locator has many advantages. In fact, it not only aids in converting online visitors into offline clients but also enhances search rankings, brand exposure, and the general buying experience.
                </p>
            </div>
        </div>
    </article>

</body>

</html>