<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Store</title>
</head>

<body>
    <header>
        <div class="row tm-top-nav tm-b-color-10">
            <div class="col-12">

                <a href="?page=search_store" class="tm-lnk-0">
                    <p class="tm-color-0 tm-txt-m tm-txt-flt-c">Store Finder</p>
                </a>

            </div>
        </div>
    </header>
    <article>
        <div class="row">
            <div class="col-12">

            </div>
        </div>
        <div class="row">
            <div class="col-12">

            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <iframe src="<?php echo $data["map"];?>"  style="border:0;" width="100%"  height="100%"  loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
            </div>
        </div>
    </article>

</body>

</html>